name = 'nxt'
description = 'A small typed raster and terminal UI library for C++.'
author = 'Mikael Brockman'
github = 'mbrock/nxtui'
cpp = 23
theme = 'dark'
main_page = true
show_includes = true
generate_tagfile = true
scripts = 'forge-doc-graphs.js'

[aliases]
"forgegraph{3}" = '@htmlonly <forge-doc-graph frg="\1" run="\2" title="\3"></forge-doc-graph> @endhtmlonly'

[sources]
extract_all = true
paths = [
    '../test',
]
recursive_paths = [
    '../src-ng',
    '../src/nxt',
    '../src/nxtai',
    '../src/nxtio',
]
patterns = [
    '*.h',
    '*.hpp',
]
strip_paths = [
    '../src-ng',
    '../src',
    '../test',
]
strip_includes = [
    '../src-ng/',
    '../src/',
]

[warnings]
treat_as_errors = false
undocumented = false
