// SPDX-License-Identifier: AGPL-3.0-or-later
// Build-time bootstrap for the executable host, not the portable library.
#include "wisp/load.hpp"
#include "wisp/printer.hpp"
#include "wisp/tape.hpp"

#include <fstream>
#include <iomanip>
#include <iostream>

namespace {

#include "wisp-host.hpp"

} // namespace

int main(int argc, char ** argv)
{
    using namespace wisp;
    try {
        if (argc != 2)
            throw std::runtime_error("expected output header path");
        auto booted = image::fresh();
        for (auto source : {base_library(), host_source}) {
            {
                loader load{booted->storage, booted->machine, source};
                auto state = evaluation::runnable;
                while (state == evaluation::runnable)
                    state = load.advance(2048);
                if (state == evaluation::failed)
                    throw std::runtime_error(print(
                        booted->storage,
                        booted->storage.get<tag::run, field::err>(
                            load.run())));
            }
            booted->machine.collect();
        }
        const auto bytes = tape::encode(booted->machine);
        std::ofstream output;
        output.exceptions(std::ios::failbit | std::ios::badbit);
        output.open(argv[1]);
        output << "// Generated by wisp-boot; do not edit.\n"
                  "constexpr char boot_tape[] =\n";
        output << std::hex << std::setfill('0');
        for (std::size_t i = 0; i < bytes.size(); ++i) {
            if (i % 16 == 0)
                output << '"';
            output << "\\x" << std::setw(2)
                   << std::to_integer<unsigned>(bytes[i]);
            if (i % 16 == 15 || i + 1 == bytes.size())
                output << "\"\n";
        }
        output << ";\n";
        output.close();
        return 0;
    } catch (const std::exception & error) {
        std::cerr << "wisp-boot: " << error.what() << '\n';
        return 1;
    }
}
